apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: target-deployment
    path: deployment-patch.yaml
  - target:
      version: v1
      kind: Service
      name: target-service
    path: service-patch.yaml