apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadrun-deployment
  labels:
    app: loadrun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadrun
  template:
    metadata:
      labels:
        app: loadrun
    spec:
      containers:
      - name: curl
        image:  alpine/curl
        # Just spin & wait forever
        command: [ "sh", "-c", "--" ]
        args: [ "while true; do sleep 1; curl http://service1.default.svc.cluster.local; done;" ]
        resources: 
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
